// Generated by gencpp from file create2/DriveRequest.msg
// DO NOT EDIT!


#ifndef CREATE2_MESSAGE_DRIVEREQUEST_H
#define CREATE2_MESSAGE_DRIVEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace create2
{
template <class ContainerAllocator>
struct DriveRequest_
{
  typedef DriveRequest_<ContainerAllocator> Type;

  DriveRequest_()
    : vel_left(0)
    , vel_right(0)  {
    }
  DriveRequest_(const ContainerAllocator& _alloc)
    : vel_left(0)
    , vel_right(0)  {
    }



   typedef int64_t _vel_left_type;
  _vel_left_type vel_left;

   typedef int64_t _vel_right_type;
  _vel_right_type vel_right;




  typedef boost::shared_ptr< ::create2::DriveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::create2::DriveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DriveRequest_

typedef ::create2::DriveRequest_<std::allocator<void> > DriveRequest;

typedef boost::shared_ptr< ::create2::DriveRequest > DriveRequestPtr;
typedef boost::shared_ptr< ::create2::DriveRequest const> DriveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::create2::DriveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::create2::DriveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace create2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::create2::DriveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::create2::DriveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::create2::DriveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::create2::DriveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create2::DriveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create2::DriveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::create2::DriveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "698bca167c703f2fed109b1244481778";
  }

  static const char* value(const ::create2::DriveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x698bca167c703f2fULL;
  static const uint64_t static_value2 = 0xed109b1244481778ULL;
};

template<class ContainerAllocator>
struct DataType< ::create2::DriveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "create2/DriveRequest";
  }

  static const char* value(const ::create2::DriveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::create2::DriveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 vel_left\n\
int64 vel_right\n\
";
  }

  static const char* value(const ::create2::DriveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::create2::DriveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel_left);
      stream.next(m.vel_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct DriveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::create2::DriveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::create2::DriveRequest_<ContainerAllocator>& v)
  {
    s << indent << "vel_left: ";
    Printer<int64_t>::stream(s, indent + "  ", v.vel_left);
    s << indent << "vel_right: ";
    Printer<int64_t>::stream(s, indent + "  ", v.vel_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CREATE2_MESSAGE_DRIVEREQUEST_H
