// Generated by gencpp from file create2/GetSensorDataRequest.msg
// DO NOT EDIT!


#ifndef CREATE2_MESSAGE_GETSENSORDATAREQUEST_H
#define CREATE2_MESSAGE_GETSENSORDATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace create2
{
template <class ContainerAllocator>
struct GetSensorDataRequest_
{
  typedef GetSensorDataRequest_<ContainerAllocator> Type;

  GetSensorDataRequest_()
    : sensor(0)  {
    }
  GetSensorDataRequest_(const ContainerAllocator& _alloc)
    : sensor(0)  {
    }



   typedef int64_t _sensor_type;
  _sensor_type sensor;




  typedef boost::shared_ptr< ::create2::GetSensorDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::create2::GetSensorDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetSensorDataRequest_

typedef ::create2::GetSensorDataRequest_<std::allocator<void> > GetSensorDataRequest;

typedef boost::shared_ptr< ::create2::GetSensorDataRequest > GetSensorDataRequestPtr;
typedef boost::shared_ptr< ::create2::GetSensorDataRequest const> GetSensorDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::create2::GetSensorDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::create2::GetSensorDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace create2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::create2::GetSensorDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::create2::GetSensorDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::create2::GetSensorDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::create2::GetSensorDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create2::GetSensorDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create2::GetSensorDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::create2::GetSensorDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24e775cf339ab5512de6ba34d3e0ff6e";
  }

  static const char* value(const ::create2::GetSensorDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24e775cf339ab551ULL;
  static const uint64_t static_value2 = 0x2de6ba34d3e0ff6eULL;
};

template<class ContainerAllocator>
struct DataType< ::create2::GetSensorDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "create2/GetSensorDataRequest";
  }

  static const char* value(const ::create2::GetSensorDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::create2::GetSensorDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sensor\n\
";
  }

  static const char* value(const ::create2::GetSensorDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::create2::GetSensorDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetSensorDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::create2::GetSensorDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::create2::GetSensorDataRequest_<ContainerAllocator>& v)
  {
    s << indent << "sensor: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sensor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CREATE2_MESSAGE_GETSENSORDATAREQUEST_H
