// Generated by gencpp from file create2/GetSensorData.msg
// DO NOT EDIT!


#ifndef CREATE2_MESSAGE_GETSENSORDATA_H
#define CREATE2_MESSAGE_GETSENSORDATA_H

#include <ros/service_traits.h>


#include <create2/GetSensorDataRequest.h>
#include <create2/GetSensorDataResponse.h>


namespace create2
{

struct GetSensorData
{

typedef GetSensorDataRequest Request;
typedef GetSensorDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSensorData
} // namespace create2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::create2::GetSensorData > {
  static const char* value()
  {
    return "535d4181008ab13e5aec6269c2d71cb0";
  }

  static const char* value(const ::create2::GetSensorData&) { return value(); }
};

template<>
struct DataType< ::create2::GetSensorData > {
  static const char* value()
  {
    return "create2/GetSensorData";
  }

  static const char* value(const ::create2::GetSensorData&) { return value(); }
};


// service_traits::MD5Sum< ::create2::GetSensorDataRequest> should match 
// service_traits::MD5Sum< ::create2::GetSensorData > 
template<>
struct MD5Sum< ::create2::GetSensorDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::create2::GetSensorData >::value();
  }
  static const char* value(const ::create2::GetSensorDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::create2::GetSensorDataRequest> should match 
// service_traits::DataType< ::create2::GetSensorData > 
template<>
struct DataType< ::create2::GetSensorDataRequest>
{
  static const char* value()
  {
    return DataType< ::create2::GetSensorData >::value();
  }
  static const char* value(const ::create2::GetSensorDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::create2::GetSensorDataResponse> should match 
// service_traits::MD5Sum< ::create2::GetSensorData > 
template<>
struct MD5Sum< ::create2::GetSensorDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::create2::GetSensorData >::value();
  }
  static const char* value(const ::create2::GetSensorDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::create2::GetSensorDataResponse> should match 
// service_traits::DataType< ::create2::GetSensorData > 
template<>
struct DataType< ::create2::GetSensorDataResponse>
{
  static const char* value()
  {
    return DataType< ::create2::GetSensorData >::value();
  }
  static const char* value(const ::create2::GetSensorDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CREATE2_MESSAGE_GETSENSORDATA_H
